version: '3'
services:
  app:
    image: 'node-react-template'
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        NODE_ENV: 'development'
    environment:
      NODE_APP_INSTANCE: 'docker'
    command: >
      sh -c "mkdir .nyc_output && npx nyc npm test
      && npx nyc report --reporter=cobertura
      && cp coverage/cobertura-coverage.xml /app/output/coverage.xml"
    depends_on:
      - db
    volumes:
      - test_output:/app/output  

  db:
    image: mongo:5.0
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'

volumes:
  test_output:

